// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: myprotocolbuffers.proto

package com.mammothdatallc.proto;

public final class MyProtocolBuffers {
  private MyProtocolBuffers() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MyProtocolBufferOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string greeting = 1;
    /**
     * <code>optional string greeting = 1;</code>
     */
    boolean hasGreeting();
    /**
     * <code>optional string greeting = 1;</code>
     */
    java.lang.String getGreeting();
    /**
     * <code>optional string greeting = 1;</code>
     */
    com.google.protobuf.ByteString
        getGreetingBytes();
  }
  /**
   * Protobuf type {@code MyProtocolBuffer}
   */
  public static final class MyProtocolBuffer extends
      com.google.protobuf.GeneratedMessage
      implements MyProtocolBufferOrBuilder {
    // Use MyProtocolBuffer.newBuilder() to construct.
    private MyProtocolBuffer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MyProtocolBuffer(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MyProtocolBuffer defaultInstance;
    public static MyProtocolBuffer getDefaultInstance() {
      return defaultInstance;
    }

    public MyProtocolBuffer getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MyProtocolBuffer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              greeting_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mammothdatallc.proto.MyProtocolBuffers.internal_static_MyProtocolBuffer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mammothdatallc.proto.MyProtocolBuffers.internal_static_MyProtocolBuffer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer.class, com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer.Builder.class);
    }

    public static com.google.protobuf.Parser<MyProtocolBuffer> PARSER =
        new com.google.protobuf.AbstractParser<MyProtocolBuffer>() {
      public MyProtocolBuffer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyProtocolBuffer(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MyProtocolBuffer> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string greeting = 1;
    public static final int GREETING_FIELD_NUMBER = 1;
    private java.lang.Object greeting_;
    /**
     * <code>optional string greeting = 1;</code>
     */
    public boolean hasGreeting() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string greeting = 1;</code>
     */
    public java.lang.String getGreeting() {
      java.lang.Object ref = greeting_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          greeting_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string greeting = 1;</code>
     */
    public com.google.protobuf.ByteString
        getGreetingBytes() {
      java.lang.Object ref = greeting_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        greeting_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      greeting_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getGreetingBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getGreetingBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MyProtocolBuffer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBufferOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mammothdatallc.proto.MyProtocolBuffers.internal_static_MyProtocolBuffer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mammothdatallc.proto.MyProtocolBuffers.internal_static_MyProtocolBuffer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer.class, com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer.Builder.class);
      }

      // Construct using com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        greeting_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mammothdatallc.proto.MyProtocolBuffers.internal_static_MyProtocolBuffer_descriptor;
      }

      public com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer getDefaultInstanceForType() {
        return com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer.getDefaultInstance();
      }

      public com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer build() {
        com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer buildPartial() {
        com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer result = new com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.greeting_ = greeting_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer) {
          return mergeFrom((com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer other) {
        if (other == com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer.getDefaultInstance()) return this;
        if (other.hasGreeting()) {
          bitField0_ |= 0x00000001;
          greeting_ = other.greeting_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mammothdatallc.proto.MyProtocolBuffers.MyProtocolBuffer) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string greeting = 1;
      private java.lang.Object greeting_ = "";
      /**
       * <code>optional string greeting = 1;</code>
       */
      public boolean hasGreeting() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string greeting = 1;</code>
       */
      public java.lang.String getGreeting() {
        java.lang.Object ref = greeting_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          greeting_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string greeting = 1;</code>
       */
      public com.google.protobuf.ByteString
          getGreetingBytes() {
        java.lang.Object ref = greeting_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          greeting_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string greeting = 1;</code>
       */
      public Builder setGreeting(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        greeting_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string greeting = 1;</code>
       */
      public Builder clearGreeting() {
        bitField0_ = (bitField0_ & ~0x00000001);
        greeting_ = getDefaultInstance().getGreeting();
        onChanged();
        return this;
      }
      /**
       * <code>optional string greeting = 1;</code>
       */
      public Builder setGreetingBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        greeting_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MyProtocolBuffer)
    }

    static {
      defaultInstance = new MyProtocolBuffer(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:MyProtocolBuffer)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MyProtocolBuffer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MyProtocolBuffer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027myprotocolbuffers.proto\"$\n\020MyProtocolB" +
      "uffer\022\020\n\010greeting\030\001 \001(\tB-\n\030com.mammothda" +
      "tallc.protoB\021MyProtocolBuffers"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_MyProtocolBuffer_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_MyProtocolBuffer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MyProtocolBuffer_descriptor,
              new java.lang.String[] { "Greeting", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
